font_family JetBrainsMono Nerd Font Mono
font_size 14
mouse_map left press ungrabbed mouse_selection normal
mouse_map ctrl+alt+left press ungrabbed mouse_selection rectangle
shell fish
cursor_shape beam
cursor_beam_thickness 2
background #1e1e2e
active_tab_background #cba6f7
inactive_tab_background #1e1e2e
tab_fade 1
tab_bar_style separator
tab_separator " | "
tab_bar_drag_threshold 9999999999
